
# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .
@base <http://purl.org/NET/cpan-uri/dist/URI-NamespaceMap/> .

<project>
    :version_from <project#main> ;
    :readme_from <project#main> ;
    :all_from <project#main> ;
    :test_requires "Test::More 0.88", "Test::Exception";
    :requires "Moose", "URI 1.52", "Try::Tiny", "Module::Load::Conditional", "Carp" ;
    :recommends "RDF::NS 20130802", "RDF::Prefixes", "XML::CommonNS" .

<project#main> <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/URI/NamespaceMap.pm" .
