
# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .
@base <http://purl.org/NET/cpan-uri/dist/URI-NamespaceMap/> .

<project>
    :version_from <project#main> ;
    :readme_from <project#main> ;
    :test_requires "Test::More 0.88" ;
    :requires "Moose", "URI 1.52" .

<project#main> <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/URI/NamespaceMap.pm" .
