# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#> .
@base <http://purl.org/NET/cpan-uri/dist/URI-NamespaceMap/> .

<project>
    :test-requirement       [ :on "Test::More 0.88"^^:CpanId ];
    :test-requirement       [ :on "Test::Exception"^^:CpanId ];
    :test-requirement       [ :on "Test::Deep"^^:CpanId ];
    :runtime-requirement    [ :on "perl 5.008001"^^:CpanId ];   # though IRI requires Perl 5.14 anyway
    :runtime-requirement    [ :on "Moo 1.006000"^^:CpanId ];
    :runtime-requirement    [ :on "URI 1.52"^^:CpanId ];
    :runtime-requirement    [ :on "IRI 0.004"^^:CpanId ];
    :runtime-requirement    [ :on "Types::URI 0.004"^^:CpanId ];
    :runtime-requirement    [ :on "Type::Library 1.000000"^^:CpanId ];
    :runtime-requirement    [ :on "Try::Tiny"^^:CpanId ];
    :runtime-requirement    [ :on "Module::Load::Conditional"^^:CpanId ];
    :runtime-requirement    [ :on "Carp"^^:CpanId ];
    :runtime-requirement    [ :on "Sub::Quote"^^:CpanId ];
    :runtime-requirement    [ :on "namespace::autoclean 0.20"^^:CpanId ];
    :runtime-recommendation [ :on "RDF::NS::Curated"^^:CpanId ];
    :runtime-recommendation [ :on "RDF::NS 20130802"^^:CpanId ];
    :runtime-recommendation [ :on "RDF::Prefixes"^^:CpanId ];
    :runtime-recommendation [ :on "XML::CommonNS"^^:CpanId ].
