name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  create:

env:
  IRC_REPO_OWNER: 'kjetilk'

jobs:
  notify:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ always() }}
    steps:
      - uses: perlrdf/devops/github-actions/irc-notifications@main
        with:
          target-notifications: true
          repository_owner: ${{ env.IRC_REPO_OWNER }}
  dist:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    name: Make distribution
    runs-on: ubuntu-latest
    outputs:
      min-perl-version: ${{ steps.build-dist.outputs.min-perl-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - id: build-dist
        uses: perlrdf/devops/github-actions/build-dist@main
        with:
          dist-perl-deps-develop: Types::URI Attean Test::Signature Test::Perl::Critic Test::Pod
  test:
    needs: [ 'dist', 'notify' ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        perl: ['5']
        inv-install-opt: [false] # Inverse install optional deps
        inv-install-ns: [false]  # Inverse install namespace deps
        include:
          - { os: 'ubuntu-latest', perl: "5"    , inv-install-opt: true, inv-install-ns: true }
          - { os: 'ubuntu-latest', perl: "5.32" }
          - { os: 'ubuntu-latest', perl: "5.30" }
          - { os: 'ubuntu-latest', perl: "5.20" }
          - { os: 'ubuntu-latest', perl: "5.16" }
          - { os: 'ubuntu-latest', perl: "5.14" }
          # Not testing this for now due to Test::Deep (requires Perl 5.12) and IRI (requires Perl 5.10)
          #- { os: 'ubuntu-latest', perl: "${{ needs.dist.outputs.min-perl-version  }}" }
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}

    steps:
      - name: Get dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        if: matrix.os != 'windows-latest'
        with:
          perl-version: ${{ matrix.perl }}
      - name: Set up perl (Strawberry)
        uses: shogo82148/actions-setup-perl@v1
        if: matrix.os == 'windows-latest'
        with:
          distribution: 'strawberry'

      - run: perl -V

      - name: Install Perl deps
        run: |
          cpanm --notest --installdeps .

      - name: Install optional deps
        if: ${{ ! matrix.inv-install-opt }}
        run: |
          cpanm --notest Attean RDF::Trine

      - name: Install namespace module deps
        if: ${{ ! matrix.inv-install-ns }}
        run: |
          # No static install opt-in specifically for RDF::NS. It appears that
          # the sharedir does not get installed on 5.14 and 5.16.
          cpanm --no-static-install --notest RDF::NS
          cpanm --notest XML::CommonNS RDF::NS::Curated RDF::NS RDF::Prefixes

      - name: Run tests
        run: |
          cpanm --verbose --test-only .
  build-status:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ always() }}
    needs: test
    steps:
      - uses: perlrdf/devops/github-actions/irc-notifications@main
        with:
          target-build-status: true
          needs: ${{ toJSON(needs) }}
          repository_owner: ${{ env.IRC_REPO_OWNER }}
